export default {
  id: 'vertical-white',
  name: '竖排白底',
  nameJa: '縦書き白背景',
  nameEn: 'Vertical White',
  thumbnail: '',
  category: 'composite',
  lockedFields: ['backgroundColor'],
  baseConfig: {
    backgroundColor: '#f5f0e8',
    texture: {
      scanline: { enabled: false, density: 2, opacity: 0.12, color: '#ffffff' },
      grain: { enabled: true, intensity: 0.08, type: 'luminance' },
    },
    textSlots: [
      {
        id: 'vertical-main',
        position: { x: 0.88, y: 0.08 },
        fontSize: 0.07,
        color: '#1a1a1a',
        direction: 'vertical',
        fontFamily: 'MS PMincho, serif',
        fontWeight: 400,
        letterSpacing: 0,
        lineHeight: 1.8,
        stagger: 0.015,
        zIndex: 0,
        enabled: true,
        border: { width: 1, color: 'rgba(0,0,0,0.12)' },
        label: '竖排文字',
        placeholder: '在此输入竖排文字…',
      },
      {
        id: 'corner',
        position: { x: 0.08, y: 0.88 },
        fontSize: 0.04,
        color: '#1a1a1a',
        direction: 'horizontal',
        fontFamily: 'MS PMincho, serif',
        fontWeight: 400,
        letterSpacing: 0.03,
        lineHeight: 1.5,
        textAlign: 'left',
        zIndex: 1,
        enabled: true,
        label: '角标文字',
        placeholder: '在此输入角标…',
      },
    ],
    footerBlock: {
      enabled: true,
      content: '— Monogatari Series —',
      position: { x: 0.5, y: 0.96 },
      fontSize: 0.025,
      color: 'rgba(0,0,0,0.5)',
      fontFamily: 'MS PMincho, serif',
      fontWeight: 400,
    },
  },
};
